# Generated by Django 5.1.1 on 2024-09-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_sar', models.CharField(max_length=100)),
                ('mot_fr', models.CharField(max_length=100)),
                ('type_mot', models.CharField(max_length=50)),
                ('phrase_sar', models.TextField()),
                ('phrase_fr', models.TextField()),
            ],
        ),
    ]
